### ISSUE TITLE
SQL Service Account Password

### ISSUE THREAD

**Issue by anwather** [PowerShell/xSqlPs#14]
Hi,

Getting an error when trying to set an account for the SQL Service account. From what I can see the /SQLSVCPASSWORD is a required field when /SQLSVCACCOUNT is specified during setup.exe.

The resource doesn't allow for the password to be added.

**Comment by kwirkykat** [comment]
@anwather Closing all issues in this repository as it has been deprecated since all the functionality is covered by xSqlServer. I think you are looking for [xSqlServerLogin](https://github.com/PowerShell/xSqlServer#xsqlserverlogin) or [xSqlServerSetup](https://github.com/PowerShell/xSqlServer#xsqlserversetup) in that module.
